have trivy print summary if no issues are found rather fail

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -26,13 +26,11 @@ inputs:
     description: "severity of issues to report"
     default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
     type: string
-  output-file:
-    description: "base filename to export scan results" 
-    default: "trivy-results"
-    type: string
 
 runs:
   using: "composite"
+  env:
+    OUTPUT-FILE: "trivy"
   steps:
 
     - name: Validate Inputs
@@ -81,13 +79,19 @@ runs:
         vuln-type: "${{ inputs.vuln-type }}"
         severity: "${{ inputs.severity }}"
         format: "json"
-        output: "trivy.json"
+        output: ${{ env.OUTPUT-FILE }}.json"
+
+    - name: Check if trivy output scan exists
+      run: |
+        if [ ! -s "${{ env.OUTPUT-FILE }}.json" ]; then
+        {
+          echo "::error::Could not find trivy results, scan failed"
+          exit 1
+        fi  
 
     - name: Convert output to Sarif for codescanning
       if: steps.ghas-enabled.output.result
       id: convert-sarif
-      env:
-        OUTPUT-FILE: ${{ inputs.output-file }}
       shell: bash
       run: |
         trivy convert --format sarif --output ${{ env.OUTPUT-FILE }}.sarif trivy.json
@@ -102,8 +106,6 @@ runs:
 
     - name: Convert output to text for github summary
       id: convert-text
-      env:
-        OUTPUT-FILE: ${{ inputs.output-file }}
       shell: bash
       run: |
         trivy convert --format table  --output ${{ env.OUTPUT-FILE }}.txt ${{ env.TRIVY_OUTPUT }}
@@ -114,18 +116,16 @@ runs:
       env:
         APP: ${{ inputs.app }}
       run: |
+        echo "### Trivy Scan Results for ${{ env.APP }}" >> $GITHUB_STEP_SUMMARY
         if [[ -s "${{ steps.convert-text.outputs.text-file }}" ]]; then
         {
-          echo "### Trivy Scan Results for ${{ env.APP }}"
           echo "<details><summary>Click to expand</summary>"
           echo ""
-          echo '```Scan results'
+          echo "```Scan results"
           cat "${{ steps.convert-text.outputs.text-file }}"
-          echo '```'
+          echo "```"
           echo "</details>"
         } >> $GITHUB_STEP_SUMMARY
-        else
-          echo "::error::Could not find trivy results. Check if container has OS information"
-          exit 1
+        elif [[ jq '.Results[]' != null && jq '.Results[].Vulnerabilities' == null ]]; then
+          echo "No issues found"
         fi
-
